apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp-deploy
  labels: 
    name: votingapp-deploy
    app:  demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: votingapp-pod
      app: demo-voting-app
  template:
    metadata:
      name: votingapp-pod
      labels:
        name: votingapp-pod
        app: demo-voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80
